"""Build the deterministic BrainBite stylized starter asset kit.

Run through Blender 5.2, not the system Python interpreter. The script keeps
all generated files inside assets/generated/blender and never touches runtime
presentation files.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import struct
import sys
from pathlib import Path

import bpy
from mathutils import Vector


PIPELINE_VERSION = "1.2.0"
DETERMINISTIC_SEED = 9021
BUILD_ID = f"brainbite-starter-kit-v{PIPELINE_VERSION}-seed-{DETERMINISTIC_SEED}"
SOURCE_SCRIPT = "scripts/blender/build_brainbite_kit.py"
LICENSE_NOTE = "Original BrainBite production asset generated by this repository pipeline."
STYLE_NOTE = "Chunky, friendly, saturated stylized mobile-game forms; original BrainBite IP."

ASSET_FILES = {
    "mascot": "brainbite_mascot.glb",
    "jungle_props": "brainbite_jungle_props.glb",
    "portal": "brainbite_portal.glb",
    "answer_pillars": "brainbite_answer_pillars.glb",
    "kraken": "brainbite_kraken.glb",
}

MATERIALS = {}
ASSETS = []


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def parse_cli() -> argparse.Namespace:
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root() / "assets" / "generated" / "blender",
        help="Generated asset root; defaults to assets/generated/blender.",
    )
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Import the existing manifest GLBs in Blender without rebuilding.",
    )
    parser.add_argument(
        "--skip-verify",
        action="store_true",
        help="Build and export without the Blender-side GLB import check.",
    )
    return parser.parse_args(argv)


def set_node_input(node, name, value) -> None:
    socket = node.inputs.get(name)
    if socket is not None:
        socket.default_value = value


def make_material(
    name: str,
    color: tuple[float, float, float, float],
    *,
    roughness: float = 0.72,
    metallic: float = 0.0,
    emission: tuple[float, float, float, float] | None = None,
    emission_strength: float = 0.0,
) -> bpy.types.Material:
    if name in MATERIALS:
        return MATERIALS[name]
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    material.diffuse_color = color
    material["brainbite_generated"] = True
    material["brainbite_build_id"] = BUILD_ID
    material["brainbite_license"] = LICENSE_NOTE
    nodes = material.node_tree.nodes
    principled = nodes.get("Principled BSDF")
    if principled is not None:
        set_node_input(principled, "Base Color", color)
        set_node_input(principled, "Roughness", roughness)
        set_node_input(principled, "Metallic", metallic)
        if emission is not None:
            set_node_input(principled, "Emission Color", emission)
            set_node_input(principled, "Emission Strength", emission_strength)
    MATERIALS[name] = material
    return material


def link_to_collection(obj: bpy.types.Object, collection: bpy.types.Collection) -> None:
    for current in list(obj.users_collection):
        current.objects.unlink(obj)
    collection.objects.link(obj)


def tag_object(
    obj: bpy.types.Object,
    asset_id: str,
    kind: str,
    root: bpy.types.Object,
    **extra,
) -> bpy.types.Object:
    obj["brainbite_generated"] = True
    obj["brainbite_asset_id"] = asset_id
    obj["brainbite_asset_root"] = root.name
    obj["brainbite_kind"] = kind
    obj["brainbite_build_id"] = BUILD_ID
    obj["brainbite_pipeline_version"] = PIPELINE_VERSION
    obj["brainbite_license"] = LICENSE_NOTE
    for key, value in extra.items():
        obj[key] = value
    return obj


def parent_keep_world(obj: bpy.types.Object, root: bpy.types.Object) -> None:
    matrix = obj.matrix_world.copy()
    obj.parent = root
    obj.matrix_world = matrix


def finish_object(
    obj: bpy.types.Object,
    collection: bpy.types.Collection,
    asset_id: str,
    kind: str,
    root: bpy.types.Object,
    *,
    material: bpy.types.Material | None = None,
    smooth: bool = False,
    **extra,
) -> bpy.types.Object:
    link_to_collection(obj, collection)
    if material is not None and obj.type == "MESH":
        obj.data.materials.append(material)
    if smooth and obj.type == "MESH":
        for polygon in obj.data.polygons:
            polygon.use_smooth = True
    parent_keep_world(obj, root)
    return tag_object(obj, asset_id, kind, root, **extra)


def add_empty(
    collection: bpy.types.Collection,
    root: bpy.types.Object,
    asset_id: str,
    name: str,
    kind: str,
    *,
    display_size: float = 0.25,
    **extra,
) -> bpy.types.Object:
    obj = bpy.data.objects.new(name, None)
    collection.objects.link(obj)
    obj.empty_display_type = "PLAIN_AXES"
    obj.empty_display_size = display_size
    parent_keep_world(obj, root)
    return tag_object(obj, asset_id, kind, root, **extra)


def add_cube(
    collection,
    asset_id,
    root,
    name,
    location,
    dimensions,
    material,
    *,
    bevel: float = 0.0,
    rotation=(0.0, 0.0, 0.0),
    kind="prop",
    **extra,
):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=location, rotation=rotation)
    obj = bpy.context.object
    obj.name = name
    obj.dimensions = dimensions
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if bevel:
        modifier = obj.modifiers.new("Soft bevel", "BEVEL")
        modifier.width = bevel
        modifier.segments = 2
        modifier.limit_method = "ANGLE"
    return finish_object(obj, collection, asset_id, kind, root, material=material, **extra)


def add_uv_sphere(
    collection,
    asset_id,
    root,
    name,
    location,
    scale,
    material,
    *,
    segments=24,
    rings=16,
    kind="prop",
    **extra,
):
    bpy.ops.mesh.primitive_uv_sphere_add(
        segments=segments,
        ring_count=rings,
        location=location,
    )
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return finish_object(
        obj,
        collection,
        asset_id,
        kind,
        root,
        material=material,
        smooth=True,
        **extra,
    )


def add_ico_sphere(
    collection,
    asset_id,
    root,
    name,
    location,
    scale,
    material,
    *,
    subdivisions=2,
    kind="prop",
    **extra,
):
    bpy.ops.mesh.primitive_ico_sphere_add(
        subdivisions=subdivisions,
        radius=1.0,
        location=location,
    )
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    return finish_object(
        obj,
        collection,
        asset_id,
        kind,
        root,
        material=material,
        smooth=True,
        **extra,
    )


def add_cylinder(
    collection,
    asset_id,
    root,
    name,
    location,
    radius,
    depth,
    material,
    *,
    vertices=16,
    rotation=(0.0, 0.0, 0.0),
    kind="prop",
    **extra,
):
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=vertices,
        radius=radius,
        depth=depth,
        location=location,
        rotation=rotation,
    )
    obj = bpy.context.object
    obj.name = name
    return finish_object(
        obj,
        collection,
        asset_id,
        kind,
        root,
        material=material,
        smooth=True,
        **extra,
    )


def add_cone(
    collection,
    asset_id,
    root,
    name,
    location,
    radius1,
    radius2,
    depth,
    material,
    *,
    vertices=12,
    rotation=(0.0, 0.0, 0.0),
    kind="prop",
    **extra,
):
    bpy.ops.mesh.primitive_cone_add(
        vertices=vertices,
        radius1=radius1,
        radius2=radius2,
        depth=depth,
        location=location,
        rotation=rotation,
    )
    obj = bpy.context.object
    obj.name = name
    return finish_object(
        obj,
        collection,
        asset_id,
        kind,
        root,
        material=material,
        smooth=True,
        **extra,
    )


def add_torus(
    collection,
    asset_id,
    root,
    name,
    location,
    major_radius,
    minor_radius,
    material,
    *,
    rotation=(0.0, 0.0, 0.0),
    kind="prop",
    **extra,
):
    bpy.ops.mesh.primitive_torus_add(
        major_segments=32,
        minor_segments=10,
        major_radius=major_radius,
        minor_radius=minor_radius,
        location=location,
        rotation=rotation,
    )
    obj = bpy.context.object
    obj.name = name
    return finish_object(
        obj,
        collection,
        asset_id,
        kind,
        root,
        material=material,
        smooth=True,
        **extra,
    )


def add_text(
    collection,
    asset_id,
    root,
    name,
    body,
    location,
    size,
    material,
    *,
    rotation=(math.radians(90.0), 0.0, 0.0),
    kind="label",
    **extra,
):
    bpy.ops.object.text_add(location=location, rotation=rotation)
    obj = bpy.context.object
    obj.name = name
    obj.data.body = body
    obj.data.align_x = "CENTER"
    obj.data.align_y = "CENTER"
    obj.data.size = size
    obj.data.extrude = 0.025
    obj.data.bevel_depth = 0.008
    bpy.ops.object.convert(target="MESH")
    return finish_object(obj, collection, asset_id, kind, root, material=material, **extra)


def add_segment(
    collection,
    asset_id,
    root,
    name,
    start,
    end,
    radius,
    material,
    *,
    kind="tentacle",
    **extra,
):
    start_vec = Vector(start)
    end_vec = Vector(end)
    delta = end_vec - start_vec
    midpoint = (start_vec + end_vec) * 0.5
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=12,
        radius=radius,
        depth=delta.length,
        location=midpoint,
    )
    obj = bpy.context.object
    obj.name = name
    obj.rotation_mode = "QUATERNION"
    obj.rotation_quaternion = delta.to_track_quat("Z", "Y")
    return finish_object(
        obj,
        collection,
        asset_id,
        kind,
        root,
        material=material,
        smooth=True,
        **extra,
    )


def new_asset(asset_id: str, display_name: str, description: str):
    scene = bpy.context.scene
    collection = bpy.data.collections.new(f"BB_{asset_id}")
    scene.collection.children.link(collection)
    root = bpy.data.objects.new(f"BrainBite_{asset_id}_ROOT", None)
    collection.objects.link(root)
    root.empty_display_type = "CUBE"
    root.empty_display_size = 0.35
    tag_object(root, asset_id, "asset_root", root, display_name=display_name)
    root["brainbite_description"] = description
    root["brainbite_style"] = STYLE_NOTE
    root["brainbite_source_script"] = SOURCE_SCRIPT
    root["brainbite_deterministic_seed"] = DETERMINISTIC_SEED
    root["brainbite_provenance_json"] = json.dumps(
        {
            "asset_id": asset_id,
            "build_id": BUILD_ID,
            "license": LICENSE_NOTE,
            "pipeline_version": PIPELINE_VERSION,
            "source_script": SOURCE_SCRIPT,
            "style": STYLE_NOTE,
        },
        sort_keys=True,
    )
    spec = {
        "asset_id": asset_id,
        "display_name": display_name,
        "description": description,
        "collection": collection,
        "root": root,
    }
    ASSETS.append(spec)
    return collection, root


def build_mascot():
    asset_id = "mascot"
    collection, root = new_asset(
        asset_id,
        "Bite Explorer Mascot",
        "Crested blue explorer with oversized eyes, compact body, and articulated idle rig.",
    )
    # Keep the character authoring pass separate from the reusable kit helpers.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from mascot_v2 import build_explorer
    build_explorer(sys.modules[__name__], collection, root)


def make_tree(collection, asset_id, root, name, x, y, z, scale):
    trunk = make_material("BB_Jungle_Trunk", (0.25, 0.11, 0.045, 1.0), roughness=0.9)
    leaf_dark = make_material("BB_Jungle_Leaf_Dark", (0.025, 0.26, 0.12, 1.0), roughness=0.86)
    leaf = make_material("BB_Jungle_Leaf", (0.06, 0.55, 0.20, 1.0), roughness=0.82)
    leaf_light = make_material("BB_Jungle_Leaf_Light", (0.25, 0.78, 0.26, 1.0), roughness=0.78)
    add_cylinder(collection, asset_id, root, f"{name}_Trunk", (x, y, z + 0.85 * scale), 0.22 * scale, 1.7 * scale, trunk, vertices=10, kind="tree_trunk")
    for index, (dx, dy, dz, s, material) in enumerate(
        [
            (-0.35, 0.0, 1.70, 0.75, leaf_dark),
            (0.30, -0.05, 1.88, 0.72, leaf),
            (0.0, 0.08, 2.20, 0.64, leaf_light),
            (0.44, 0.12, 2.22, 0.44, leaf),
            (-0.44, -0.04, 2.04, 0.45, leaf_light),
        ],
        start=1,
    ):
        add_ico_sphere(collection, asset_id, root, f"{name}_Canopy_{index:02d}", (x + dx * scale, y + dy * scale, z + dz * scale), (s * scale, s * 0.82 * scale, s * 0.78 * scale), material, subdivisions=1, kind="tree_canopy")


def build_jungle_props():
    asset_id = "jungle_props"
    collection, root = new_asset(
        asset_id,
        "Bite Village Jungle Props",
        "Reusable low-poly trees, rocks, fern, reward chest, and village sign.",
    )
    make_tree(collection, asset_id, root, "JungleTree_A", -3.0, 0.25, 0.0, 1.05)
    make_tree(collection, asset_id, root, "JungleTree_B", 2.75, 0.40, 0.0, 0.82)
    trunk = make_material("BB_Jungle_Trunk", (0.25, 0.11, 0.045, 1.0), roughness=0.9)
    stone = make_material("BB_Jungle_Stone", (0.29, 0.34, 0.36, 1.0), roughness=0.92)
    stone_light = make_material("BB_Jungle_Stone_Light", (0.45, 0.52, 0.48, 1.0), roughness=0.88)
    leaf = make_material("BB_Jungle_Leaf", (0.06, 0.55, 0.20, 1.0), roughness=0.82)
    fern = make_material("BB_Jungle_Fern", (0.15, 0.68, 0.20, 1.0), roughness=0.78)
    chest = make_material("BB_Jungle_Chest", (0.65, 0.26, 0.045, 1.0), roughness=0.66)
    chest_gold = make_material("BB_Jungle_Chest_Gold", (1.0, 0.67, 0.05, 1.0), roughness=0.36, metallic=0.3)
    sign = make_material("BB_Jungle_Sign", (0.47, 0.20, 0.06, 1.0), roughness=0.82)
    cream = make_material("BB_Jungle_SignText", (1.0, 0.88, 0.46, 1.0), roughness=0.5)
    add_ico_sphere(collection, asset_id, root, "JungleRock_A", (-1.55, 0.30, 0.38), (0.75, 0.56, 0.38), stone, subdivisions=1, kind="rock")
    add_ico_sphere(collection, asset_id, root, "JungleRock_B", (1.35, -0.10, 0.30), (0.48, 0.36, 0.28), stone_light, subdivisions=1, kind="rock")
    add_cylinder(collection, asset_id, root, "JungleStump", (0.0, 1.45, 0.32), 0.48, 0.64, trunk, vertices=10, kind="stump")
    add_cylinder(collection, asset_id, root, "JungleStumpTop", (0.0, 1.45, 0.66), 0.45, 0.07, stone_light, vertices=10, kind="stump_top")
    for index, angle in enumerate((-0.9, -0.45, 0.0, 0.45, 0.9), start=1):
        x = 1.0 + math.sin(angle) * 0.65
        y = 1.9 + math.cos(angle) * 0.28
        z = 0.45 + abs(angle) * 0.05
        add_cone(collection, asset_id, root, f"Fern_{index:02d}", (x, y, z), 0.18, 0.02, 1.0, fern, rotation=(0.2 * math.cos(angle), angle * 0.35, angle * 0.7), vertices=7, kind="fern_leaf")
    add_cube(collection, asset_id, root, "RewardChest_Body", (1.55, -1.20, 0.40), (1.15, 0.72, 0.65), chest, bevel=0.10, kind="reward_chest")
    add_cube(collection, asset_id, root, "RewardChest_Lid", (1.55, -1.20, 0.82), (1.17, 0.74, 0.18), chest, bevel=0.08, rotation=(math.radians(-8), 0, 0), kind="reward_chest_lid")
    add_cube(collection, asset_id, root, "RewardChest_Band", (1.55, -1.58, 0.46), (0.16, 0.08, 0.72), chest_gold, bevel=0.02, kind="reward_chest_band")
    add_ico_sphere(collection, asset_id, root, "RewardChest_Gem", (1.55, -1.65, 0.80), (0.13, 0.05, 0.13), cream, kind="reward_chest_gem")
    add_cylinder(collection, asset_id, root, "VillageSign_Post", (-0.10, -1.60, 0.92), 0.10, 1.85, trunk, vertices=8, kind="sign_post")
    add_cube(collection, asset_id, root, "VillageSign_Board", (-0.10, -1.60, 1.72), (2.15, 0.16, 0.66), sign, bevel=0.08, kind="sign_board")
    add_text(collection, asset_id, root, "VillageSign_Label", "BITE VILLAGE", (-0.10, -1.705, 1.73), 0.28, cream, kind="sign_label")
    add_empty(collection, root, asset_id, "JungleProps_Socket_Ground", "socket", display_size=0.18, socket="ground")


def build_portal():
    asset_id = "portal"
    collection, root = new_asset(
        asset_id,
        "Play Portal",
        "Chunky stone arch with an emissive turquoise learning gateway.",
    )
    stone = make_material("BB_Portal_Stone", (0.34, 0.28, 0.24, 1.0), roughness=0.9)
    stone_light = make_material("BB_Portal_Stone_Light", (0.58, 0.46, 0.31, 1.0), roughness=0.84)
    portal = make_material("BB_Portal_Energy", (0.02, 0.66, 0.92, 1.0), roughness=0.22, emission=(0.01, 0.42, 1.0, 1.0), emission_strength=2.8)
    portal_dark = make_material("BB_Portal_Energy_Dark", (0.02, 0.18, 0.42, 1.0), roughness=0.30, emission=(0.01, 0.08, 0.24, 1.0), emission_strength=1.0)
    gold = make_material("BB_Portal_Gold", (1.0, 0.63, 0.08, 1.0), roughness=0.42, metallic=0.25)
    cream = make_material("BB_Portal_Label", (1.0, 0.92, 0.62, 1.0), roughness=0.45)
    add_cube(collection, asset_id, root, "Portal_LeftPillar", (-1.05, 0, 1.25), (0.58, 0.86, 2.50), stone, bevel=0.15, kind="portal_stone")
    add_cube(collection, asset_id, root, "Portal_RightPillar", (1.05, 0, 1.25), (0.58, 0.86, 2.50), stone, bevel=0.15, kind="portal_stone")
    add_cube(collection, asset_id, root, "Portal_TopBeam", (0, 0, 2.49), (2.62, 0.86, 0.50), stone_light, bevel=0.16, kind="portal_stone")
    add_torus(collection, asset_id, root, "Portal_OuterRune", (0, -0.48, 1.35), 1.02, 0.10, gold, rotation=(math.radians(90), 0, 0), kind="portal_rune")
    add_cylinder(collection, asset_id, root, "Portal_EnergyField", (0, -0.05, 1.35), 0.88, 0.10, portal_dark, vertices=32, rotation=(math.radians(90), 0, 0), kind="portal_energy")
    add_torus(collection, asset_id, root, "Portal_EnergyRing", (0, -0.49, 1.35), 0.70, 0.08, portal, rotation=(math.radians(90), 0, 0), kind="portal_energy")
    add_torus(collection, asset_id, root, "Portal_EnergyRing_Inner", (0, -0.52, 1.35), 0.42, 0.045, portal, rotation=(math.radians(90), 0, 0), kind="portal_energy")
    for side in (-1, 1):
        prefix = "L" if side < 0 else "R"
        for index, z in enumerate((0.42, 1.0, 1.58, 2.08), start=1):
            add_ico_sphere(collection, asset_id, root, f"Portal_{prefix}_Rune_{index:02d}", (side * 1.36, -0.48, z), (0.10, 0.08, 0.10), gold, kind="portal_rune")
    add_text(collection, asset_id, root, "Portal_Label", "PLAY PORTAL", (0, -0.50, 3.15), 0.42, cream, kind="portal_label")
    add_empty(collection, root, asset_id, "Portal_Socket_Entry", "socket", display_size=0.18, socket="entry")
    add_empty(collection, root, asset_id, "Portal_Socket_Exit", "socket", display_size=0.18, socket="exit", location_hint="forward")


def make_answer_pillar(collection, asset_id, root, index, label, x):
    stone = make_material("BB_Pillar_Stone", (0.24, 0.33, 0.43, 1.0), roughness=0.84)
    stone_light = make_material("BB_Pillar_Stone_Light", (0.48, 0.59, 0.66, 1.0), roughness=0.70)
    accent = make_material("BB_Pillar_Accent", (0.07, 0.62, 0.84, 1.0), roughness=0.28, emission=(0.02, 0.30, 0.75, 1.0), emission_strength=1.8)
    label_mat = make_material("BB_Pillar_Label", (1.0, 0.88, 0.42, 1.0), roughness=0.38)
    prefix = f"Pillar_{index:02d}"
    add_cube(collection, asset_id, root, f"{prefix}_Base", (x, 0, 0.18), (1.15, 1.00, 0.36), stone, bevel=0.12, kind="answer_pillar_base", answer_slot=label)
    add_cylinder(collection, asset_id, root, f"{prefix}_Shaft", (x, 0, 1.05), 0.42, 1.55, stone, vertices=8, kind="answer_pillar_shaft", answer_slot=label)
    add_cube(collection, asset_id, root, f"{prefix}_Top", (x, 0, 1.92), (1.00, 0.92, 0.26), stone_light, bevel=0.08, kind="answer_pillar_top", answer_slot=label)
    add_torus(collection, asset_id, root, f"{prefix}_Ring", (x, 0, 2.11), 0.34, 0.055, accent, kind="answer_pillar_ring", answer_slot=label)
    add_ico_sphere(collection, asset_id, root, f"{prefix}_Gem", (x, -0.01, 2.28), (0.22, 0.22, 0.22), accent, kind="answer_pillar_gem", answer_slot=label)
    add_cube(collection, asset_id, root, f"{prefix}_AnswerPlate", (x, -0.48, 1.18), (0.76, 0.10, 0.56), stone_light, bevel=0.05, kind="answer_pillar_plate", answer_slot=label)
    add_text(collection, asset_id, root, f"{prefix}_AnswerLabel", label, (x, -0.555, 1.19), 0.36, label_mat, kind="answer_pillar_label", answer_slot=label)


def build_answer_pillars():
    asset_id = "answer_pillars"
    collection, root = new_asset(
        asset_id,
        "Answer Pillar Set",
        "Four reusable answer pillars with stable A-D slots for math challenge presentation.",
    )
    for index, (label, x) in enumerate(zip(("A", "B", "C", "D"), (-2.7, -0.9, 0.9, 2.7)), start=1):
        make_answer_pillar(collection, asset_id, root, index, label, x)
    add_empty(collection, root, asset_id, "AnswerPillars_Socket_Player", "socket", display_size=0.18, socket="player")


def build_kraken():
    asset_id = "kraken"
    collection, root = new_asset(
        asset_id,
        "Fraction Kraken",
        "Friendly but formidable purple jungle boss with eight readable tentacles.",
    )
    purple = make_material("BB_Kraken_Purple", (0.30, 0.08, 0.56, 1.0), roughness=0.60)
    purple_dark = make_material("BB_Kraken_Purple_Dark", (0.12, 0.025, 0.28, 1.0), roughness=0.68)
    teal = make_material("BB_Kraken_Teal", (0.02, 0.55, 0.58, 1.0), roughness=0.42)
    yellow = make_material("BB_Kraken_Eye", (1.0, 0.78, 0.08, 1.0), roughness=0.32, emission=(1.0, 0.36, 0.02, 1.0), emission_strength=1.6)
    black = make_material("BB_Kraken_Mouth", (0.025, 0.012, 0.07, 1.0), roughness=0.38)
    tooth = make_material("BB_Kraken_Tooth", (1.0, 0.88, 0.58, 1.0), roughness=0.50)
    sucker = make_material("BB_Kraken_Sucker", (0.92, 0.28, 0.42, 1.0), roughness=0.58)
    add_ico_sphere(collection, asset_id, root, "Kraken_Mantle", (0, 0, 2.00), (1.55, 1.08, 1.18), purple, subdivisions=2, kind="boss_body")
    add_uv_sphere(collection, asset_id, root, "Kraken_Belly", (0, -0.92, 1.82), (1.08, 0.16, 0.86), teal, kind="boss_belly")
    add_uv_sphere(collection, asset_id, root, "Kraken_Mouth", (0, -1.10, 1.55), (0.70, 0.10, 0.34), black, kind="boss_mouth")
    for side in (-1, 1):
        prefix = "L" if side < 0 else "R"
        add_uv_sphere(collection, asset_id, root, f"Kraken_{prefix}_Eye", (side * 0.48, -0.95, 2.37), (0.26, 0.13, 0.33), yellow, kind="boss_eye")
        add_uv_sphere(collection, asset_id, root, f"Kraken_{prefix}_Pupil", (side * 0.48, -1.08, 2.38), (0.07, 0.035, 0.15), black, kind="boss_pupil")
        add_cone(collection, asset_id, root, f"Kraken_{prefix}_CrownHorn", (side * 0.78, 0.0, 3.08), 0.28, 0.02, 0.72, teal, rotation=(0, side * 0.30, 0), vertices=8, kind="boss_horn")
    for index, x in enumerate((-0.42, -0.14, 0.14, 0.42), start=1):
        add_cone(collection, asset_id, root, f"Kraken_Tooth_{index:02d}", (x, -1.20, 1.58), 0.08, 0.0, 0.24, tooth, vertices=8, rotation=(math.radians(180), 0, 0), kind="boss_tooth")
    add_torus(collection, asset_id, root, "Kraken_CrownBand", (0, 0, 2.84), 0.88, 0.08, teal, kind="boss_crown")
    for index in range(8):
        angle = math.radians(index * 45.0 + 22.5)
        direction = Vector((math.cos(angle), math.sin(angle), 0.0))
        start = Vector((direction.x * 0.60, direction.y * 0.60, 1.10))
        mid = Vector((direction.x * 1.35, direction.y * 1.35, 0.52 + 0.08 * (index % 2)))
        end = Vector((direction.x * 2.25, direction.y * 2.25, 0.26 + 0.04 * (index % 3)))
        tip = Vector((direction.x * 2.70, direction.y * 2.70, 0.20))
        add_segment(collection, asset_id, root, f"Kraken_Tentacle_{index + 1:02d}_A", start, mid, 0.28, purple_dark, tentacle_index=index + 1)
        add_segment(collection, asset_id, root, f"Kraken_Tentacle_{index + 1:02d}_B", mid, end, 0.21, purple, tentacle_index=index + 1)
        add_segment(collection, asset_id, root, f"Kraken_Tentacle_{index + 1:02d}_C", end, tip, 0.13, purple, tentacle_index=index + 1)
        add_uv_sphere(collection, asset_id, root, f"Kraken_Tentacle_{index + 1:02d}_Joint", mid, (0.28, 0.28, 0.28), purple_dark, subdivisions=1, kind="tentacle_joint", tentacle_index=index + 1)
        for sucker_index, fraction in enumerate((0.34, 0.66), start=1):
            point = start.lerp(mid, fraction) + Vector((0, 0, 0.13))
            add_uv_sphere(collection, asset_id, root, f"Kraken_Sucker_{index + 1:02d}_{sucker_index:02d}", point, (0.08, 0.04, 0.08), sucker, subdivisions=1, kind="tentacle_sucker", tentacle_index=index + 1)
    add_ico_sphere(collection, asset_id, root, "Kraken_CrownGem", (0, -0.10, 3.05), (0.16, 0.16, 0.21), yellow, kind="boss_gem")
    add_text(collection, asset_id, root, "Kraken_Nameplate", "FRACTION KRAKEN", (0, -1.13, 3.45), 0.32, yellow, kind="boss_nameplate")
    add_empty(collection, root, asset_id, "Kraken_Socket_Arena", "socket", display_size=0.20, socket="arena")


def add_preview_collection() -> None:
    collection = bpy.data.collections.new("BB_PREVIEW_ONLY")
    bpy.context.scene.collection.children.link(collection)
    camera_data = bpy.data.cameras.new("BB_PreviewCameraData")
    camera = bpy.data.objects.new("BB_PreviewCamera", camera_data)
    collection.objects.link(camera)
    camera.location = (8.0, -12.0, 7.0)
    camera_data.lens = 50
    camera["brainbite_preview_only"] = True
    light_data = bpy.data.lights.new("BB_PreviewKeyData", type="AREA")
    key = bpy.data.objects.new("BB_PreviewKey", light_data)
    collection.objects.link(key)
    key.location = (4.0, -5.0, 8.0)
    light_data.energy = 900
    light_data.shape = "DISK"
    light_data.size = 5.0
    fill_data = bpy.data.lights.new("BB_PreviewFillData", type="AREA")
    fill = bpy.data.objects.new("BB_PreviewFill", fill_data)
    collection.objects.link(fill)
    fill.location = (-5.0, -3.0, 4.0)
    fill_data.energy = 500
    fill_data.size = 4.0


def reset_scene() -> None:
    random.seed(DETERMINISTIC_SEED)
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.length_unit = "METERS"
    # Blender 5.2.1 exposes the current Eevee engine under this stable ID.
    scene.render.engine = "BLENDER_EEVEE"
    scene["brainbite_build_id"] = BUILD_ID
    scene["brainbite_pipeline_version"] = PIPELINE_VERSION
    scene["brainbite_deterministic_seed"] = DETERMINISTIC_SEED
    scene["brainbite_source_script"] = SOURCE_SCRIPT
    scene["brainbite_license"] = LICENSE_NOTE
    scene["brainbite_style"] = STYLE_NOTE


def call_supported(operator, kwargs):
    properties = operator.get_rna_type().properties.keys()
    return operator(**{key: value for key, value in kwargs.items() if key in properties})


def select_asset(spec) -> None:
    bpy.ops.object.select_all(action="DESELECT")
    for obj in spec["collection"].objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = spec["root"]


def export_asset(spec, output_path: Path) -> dict:
    select_asset(spec)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    call_supported(
        bpy.ops.export_scene.gltf,
        {
            "filepath": str(output_path),
            "export_format": "GLB",
            "use_selection": True,
            "export_apply": True,
            "export_materials": "EXPORT",
            "export_animations": True,
            "export_animation_mode": "ACTIONS",
            "export_cameras": False,
            "export_lights": False,
            "export_extras": True,
        },
    )
    if not output_path.is_file() or output_path.stat().st_size < 32:
        raise RuntimeError(f"Blender did not produce a usable GLB: {output_path}")
    with output_path.open("rb") as handle:
        header = handle.read(12)
    if header[:4] != b"glTF" or struct.unpack("<I", header[4:8])[0] != 2:
        raise RuntimeError(f"Invalid GLB header: {output_path}")
    objects = list(spec["collection"].objects)
    mesh_count = sum(obj.type == "MESH" for obj in objects)
    material_names = sorted(
        {
            material.name
            for obj in objects
            if obj.type == "MESH"
            for material in obj.data.materials
            if material is not None
        }
    )
    return {
        "asset_id": spec["asset_id"],
        "display_name": spec["display_name"],
        "description": spec["description"],
        "file": output_path.name,
        "root_object": spec["root"].name,
        "object_count": len(objects),
        "mesh_count": mesh_count,
        "material_names": material_names,
        "size_bytes": output_path.stat().st_size,
        "sha256": hashlib.sha256(output_path.read_bytes()).hexdigest(),
    }


def import_verify(path: Path) -> dict:
    if not path.is_file():
        raise RuntimeError(f"Missing GLB: {path}")
    raw = path.read_bytes()
    if len(raw) < 20 or raw[:4] != b"glTF" or struct.unpack("<I", raw[4:8])[0] != 2:
        raise RuntimeError(f"Invalid GLB header: {path}")
    reset_scene()
    if not hasattr(bpy.ops.import_scene, "gltf"):
        raise RuntimeError("Blender glTF importer is unavailable")
    call_supported(bpy.ops.import_scene.gltf, {"filepath": str(path)})
    imported = list(bpy.context.scene.objects)
    mesh_count = sum(obj.type == "MESH" for obj in imported)
    if mesh_count < 1:
        raise RuntimeError(f"GLB imported without mesh geometry: {path}")
    return {
        "file": path.name,
        "header": "glTF v2",
        "imported_object_count": len(imported),
        "imported_mesh_count": mesh_count,
    }


def write_json(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build(output_root: Path, skip_verify: bool) -> None:
    output_root = output_root.resolve()
    source_dir = output_root / "source"
    glb_dir = output_root / "glb"
    source_dir.mkdir(parents=True, exist_ok=True)
    glb_dir.mkdir(parents=True, exist_ok=True)
    reset_scene()
    ASSETS.clear()
    MATERIALS.clear()
    build_mascot()
    build_jungle_props()
    build_portal()
    build_answer_pillars()
    build_kraken()
    add_preview_collection()
    source_blend = source_dir / "brainbite_starter_kit.blend"
    bpy.ops.wm.save_as_mainfile(filepath=str(source_blend))
    output_records = []
    for spec in ASSETS:
        output_records.append(export_asset(spec, glb_dir / ASSET_FILES[spec["asset_id"]]))
    manifest = {
        "schema": "brainbite.blender.asset-manifest.v1",
        "build_id": BUILD_ID,
        "pipeline_version": PIPELINE_VERSION,
        "blender_version": bpy.app.version_string,
        "deterministic_seed": DETERMINISTIC_SEED,
        "source_script": SOURCE_SCRIPT,
        "source_blend": "assets/generated/blender/source/brainbite_starter_kit.blend",
        "supporting_source_scripts": ["scripts/blender/mascot_v2.py"],
        "output_directory": "assets/generated/blender/glb",
        "license": LICENSE_NOTE,
        "style": STYLE_NOTE,
        "assets": output_records,
    }
    manifest_path = output_root / "manifest.json"
    if not skip_verify:
        manifest["verification"] = {
            "method": "Blender 5.2 headless glTF import",
            "status": "passed",
            "files": [import_verify(glb_dir / record["file"]) for record in output_records],
        }
    else:
        manifest["verification"] = {"method": "skipped by --skip-verify", "status": "skipped"}
    write_json(manifest_path, manifest)
    print(f"BUILD PASS {BUILD_ID}")
    print(f"SOURCE {source_blend}")
    for record in output_records:
        print(f"GLB {record['file']} {record['size_bytes']} bytes sha256={record['sha256']}")
    print(f"MANIFEST {manifest_path}")
    print(f"VERIFY {manifest['verification']['status']}")


def verify_existing(output_root: Path) -> None:
    manifest_path = output_root.resolve() / "manifest.json"
    if not manifest_path.is_file():
        raise RuntimeError(f"Missing manifest: {manifest_path}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    glb_dir = output_root.resolve() / "glb"
    results = []
    for asset in manifest.get("assets", []):
        path = glb_dir / asset["file"]
        result = import_verify(path)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != asset.get("sha256"):
            raise RuntimeError(f"SHA-256 mismatch for {path.name}")
        results.append(result)
    if len(results) != len(ASSET_FILES):
        raise RuntimeError(f"Expected {len(ASSET_FILES)} manifest assets, found {len(results)}")
    print(f"VERIFY PASS {manifest['build_id']}")
    for result in results:
        print(f"IMPORT PASS {result['file']} objects={result['imported_object_count']} meshes={result['imported_mesh_count']}")


def main() -> None:
    args = parse_cli()
    try:
        if args.verify_only:
            verify_existing(args.output)
        else:
            build(args.output, args.skip_verify)
    except Exception as exc:
        print(f"BUILD FAIL {type(exc).__name__}: {exc}", file=sys.stderr)
        raise


if __name__ == "__main__":
    main()
